services:
  postgres:
    image: postgres:16
    container_name: library-postgres
    ports:
      - "${DB_PORT}:5432"
    environment:
      POSTGRES_DB: "${DB_NAME}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_USER: "${DB_USER}"
    volumes:
      - postgres:/var/lib/postgresql/data

  adminer:
    image: adminer
    ports:
      - "${DB_ADMINER_PORT}:8080"

  redis:
    image: redis:7
    container_name: library-redis
    command: "--save 60 1 --loglevel warning --requirepass ${REDIS_PASSWORD}"
    ports:
      - "${REDIS_PORT}:6379"
    environment:
      TZ: UTC
    volumes:
      - redis:/data

volumes:
  postgres:
  redis:
