version: 3

tasks:
  start:
    cmds:
      - docker compose up -d
      - task: wait-redis
      - task: wait-db

  wait-db:
    cmds:
      - cmd: docker run --rm --add-host=host.docker.internal:host-gateway -e WAIT_LOGGER_LEVEL=error -e WAIT_HOSTS=host.docker.internal:$DB_PORT ghcr.io/ufoscout/docker-compose-wait:latest /wait
        silent: true
      - cmd: echo "DB is ready on $DB_PORT port."
        silent: true
    dotenv: [".env"]

  wait-redis:
    cmds:
      - cmd: docker run --rm --add-host=host.docker.internal:host-gateway -e WAIT_LOGGER_LEVEL=error -e WAIT_HOSTS=host.docker.internal:$REDIS_PORT ghcr.io/ufoscout/docker-compose-wait:latest /wait
        silent: true
      - cmd: echo "Redis is ready on $REDIS_PORT port."
        silent: true
    dotenv: [".env"]

  log:
    cmds:
      - docker compose logs -f

  stop:
    cmds:
      - docker compose stop

  rm:
    cmds:
      - docker compose down --remove-orphans --volumes

  db:
    cmds:
      - cmd: docker compose exec -e PGPASSWORD=$DB_PASSWORD postgres psql -h localhost -U $DB_USER
        silent: true
    dotenv: [".env"]

  db-bash:
    cmds:
      - docker compose exec postgres bash

  redis:
    cmds:
      - cmd: docker compose exec redis redis-cli -a "$REDIS_PASSWORD"
        silent: true
    dotenv: [".env"]
