version: 3

includes:
  compose:
    taskfile: tools/docker-compose/Taskfile.yml
    dir: tools/docker-compose

tasks:
  install:
    summary: "install dependencies"
    cmds:
      - mix deps.get

  run:
    summary: "run dev server"
    cmds:
      - mix phx.server

  iex:
    summary: "run IEx"
    cmds:
      - iex -S mix

  #---------------------------------
  # Web
  #---------------------------------

  routes:
    summary: "display routes"
    cmds:
      - mix phx.routes LibraryWeb.Router

  #---------------------------------
  # DB
  #---------------------------------

  db-migrate:
    summary: "migrate DB schema"
    dir: apps/library_web
    cmds:
      - mix ecto.migrate

  db-rollback-1:
    summary: "rollback DB schema migration 1 step"
    dir: apps/library_web
    cmds:
      - mix ecto.rollback --step 1

  db-seed-data:
    summary: "insert seed data"
    dir: apps/library
    cmds:
      - mix run priv/repo/seeds.exs

  db-psql:
    summary: "connect to postgres"
    cmds:
      - task: compose:db

  db-start:
    summary: "start DB"
    cmds:
      - task: compose:start
      - task: db-migrate

  db-stop:
    summary: "stop DB"
    cmds:
      - task: compose:stop

  db-rm:
    summary: "remove DB"
    cmds:
      - task: compose:rm

  #---------------------------------
  # Docker
  #---------------------------------

  docker-build:
    summary: "build docker image"
    cmds:
      - docker build -t library .

  docker-run:
    summary: "run production docker container against docker compose database and redis"
    cmds:
      - docker run --rm -e SECRET_KEY_BASE=$(mix phx.gen.secret) -e DATABASE_URL={{.DATABASE_URL}} -p 4002:4000 library start
    vars:
      DATABASE_URL: ecto://library:Passw0rd@host.docker.internal/library
